FROM node:10.13.0-alpine
RUN mkdir -p /app/config /app/src
WORKDIR /app
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY server.js /app/server.js
RUN npm install
EXPOSE 3005
CMD ["npm", "run", "start"]